#!/bin/bash
# Install the pre-push hook. Run once after a fresh clone (.git/hooks/ isn't tracked).
# Usage: ./scripts/hooks/install.sh
#
# This installs a SHIM, not a copy. A copy goes stale the moment anyone edits the
# tracked hook, and it goes stale silently: pushes keep succeeding while the checks
# you think you added never run. That happened here between 2026-07-28 and
# 2026-09-09 (known-bugs R16). The shim execs the tracked file, so an edit to
# scripts/hooks/pre-push takes effect on the very next push with no reinstall.
set -euo pipefail
cd "$(dirname "$0")/../.."

cat > .git/hooks/pre-push <<'SHIM'
#!/bin/bash
# Generated by scripts/hooks/install.sh — do not edit, edit scripts/hooks/pre-push.
set -euo pipefail
src="$(git rev-parse --show-toplevel)/scripts/hooks/pre-push"
if [ ! -x "$src" ]; then
  echo "pre-push: $src is missing or not executable — refusing to push unchecked" >&2
  exit 1
fi
exec "$src" "$@"
SHIM

chmod +x .git/hooks/pre-push
echo "Installed .git/hooks/pre-push (shim → scripts/hooks/pre-push)"
